apiVersion: v2
name: inference-stack
description: A Helm chart for deploying a inference stack in kubernetes
icon: https://raw.githubusercontent.com/titanml/titanml-public-assets/refs/heads/master/TitanML-Icon-1000x1001.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0

# This is the version number of the Takeoff Engine being deployed inside the inference stack. This version number should be
# incremented each time you wish to deploy a different version of Takeoff Engine as default. 
# The gateway will append this version with "-cpu", and the applications will append this version with "-gpu".
# If you wish to override this behaviour, or deploy different versions of the gateway and apps,
# you can do so by setting the gateway.image.tag and applications.image.tag respectively.
appVersion: "0.22.0-rc19"
