# Postgres Database
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "console.fullname" . }}-db
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  serviceName: {{ include "console.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "console.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        {{- include "console.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secret.generate }} {{ include "console.fullname" . }}-{{ .Values.secret.name }} {{ else }} {{ .Values.secret.name }} {{ end}}
              key: {{ .Values.secret.keys.dbUser }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secret.generate }} {{ include "console.fullname" . }}-{{ .Values.secret.name }} {{ else }} {{ .Values.secret.name }} {{ end}}
              key: {{ .Values.secret.keys.dbPassword }}
        - name: POSTGRES_DB
          value: zeus
        - name: PGDATA
          value: /data/pgdata
        volumeMounts:
        - name: {{ include "console.fullname" . }}-db
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: {{ include "console.fullname" . }}-db
      labels:
        {{- include "console.labels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      {{- .Values.db.volumeSpec | toYaml | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-db
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app.kubernetes.io/component: db
    {{- include "console.selectorLabels" . | nindent 4 }}
