{{ if .Values.secret.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.fullname" . }}-{{.Values.secret.name}}
type: Opaque
stringData:
  dbUser: "postgres"
  dbPassword: "postgres"
{{ end }}
